# Generated by Django 6.0.7 on 2026-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(max_length=20)),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
