# Generated by Django 6.0.7 on 2026-08-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
