# Generated by Django 6.0.7 on 2026-08-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('activity', models.CharField(max_length=30)),
                ('goal', models.CharField(max_length=30)),
                ('diet', models.CharField(max_length=30)),
                ('medical_conditions', models.TextField(blank=True)),
                ('dietary_restrictions', models.TextField(blank=True)),
            ],
        ),
    ]
